import { Request } from 'express';
import { ObjectId } from 'mongodb';
import { DatabaseNotification, Notification } from './notification';

/**
 * Represents user credentials for authentication.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 */
export interface UserCredentials {
  username: string;
  password?: string;
}

/**
 * Represents a user document, including user credentials and additional details.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `biography`: A short description or bio of the user (optional).
 * - `profilePicture`: URL/path to user's profile picture.
 * - `bannerImage`: URL/path to user's banner image.
 * - `oauthProvider`: OAuth provider used ('local', 'google', 'github').
 * - `oauthId`: ID from OAuth provider.
 * - `badges`: Array of badge IDs the user has earned.
 * - `displayedBadges`: Array of badge IDs the user wants to display.
 * - `loginStreak`: Number of consecutive days logged in.
 * - `maxLoginStreak`: Maximum login streak ever achieved.
 * - `lastLogin`: The last date/time the user logged in.
 * - `showLoginStreak`: Whether to display the login streak on profile.
 * - `email`: Email associated with user.
 * - `lifeUpvotes`: Lifetime upvotes to user's posts (answers & questions).
 * - `coins`: Amount of coins user currently has.
 * - `profilePrivate`: Whether the user's profile is private.
 * - `premiumProfile`: Whether the user has a premium profile or not.
 * - `streakPass`: Number of passes user has to miss streak.
 * - `missedDays`: Number of days user has not logged in for.
 * - `streakHold`: Whether streak is currently on hold to be recovered.
 * - `status`: User's current status ('online', 'busy', 'away').
 * - `customStatus`: Custom status message.
 * - `communityNotifs`: Whether notifications are enabled for all communities.
 * - `messageNotifs`: Whether notifications are enabled for all users.
 */
export interface User extends UserCredentials {
  dateJoined: Date;
  biography?: string;
  profilePicture?: string;
  bannerImage?: string;
  oauthProvider?: 'local' | 'google' | 'github';
  oauthId?: string;
  badges?: ObjectId[];
  displayedBadges?: ObjectId[];
  loginStreak?: number;
  maxLoginStreak?: number;
  lastLogin?: Date;
  showLoginStreak?: boolean;
  email?: string;
  roles?: Map<string, string>;
  lifeUpvotes?: number;
  coins?: number;
  profilePrivate?: boolean;
  notifications?: UserNotificationStatus[];
  premiumProfile?: boolean;
  streakPass?: number;
  missedDays?: number;
  streakHold?: boolean;
  status?: 'online' | 'busy' | 'away';
  customStatus?: string;
  notifications?: Notification[];
  communityNotifs?: boolean;
  messageNotifs?: boolean;
}

/**
 * Represents a user document in the database.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `biography`: A short description or bio of the user (optional).
 * - `_id`: The unique identifier for the user, generated by MongoDB.
 */
export interface DatabaseUser extends Omit<User, 'notifications'> {
  _id: ObjectId;
  notifications?: DatabaseUserNotificationStatus[];
}

export interface UserNotificationStatus {
  notificiation: Notification;
  read: boolean;
}

export interface DatabaseUserNotificationStatus {
  notification: ObjectId;
  read: boolean;
}

export interface PopulatedUserNotificationStatus {
  notification: DatabaseNotification;
  read: boolean;
}

/**
 * Express request for user login, containing user credentials.
 * - `username`: The username submitted in the request (body).
 * - `password`: The password submitted in the request (body).
 * - `biography`: Optional field for biography information (body).
 */
export interface UserRequest extends Request {
  body: {
    username: string;
    password: string;
    biography?: string;
  };
}

/**
 * Express request for querying a user by their username.
 * - `username`: The username provided as a route parameter.
 */
export interface UserByUsernameRequest extends Request {
  params: {
    username: string;
  };
}

/**
 * Represents a "safe" user object that excludes sensitive information like the password.
 */
export interface PopulatedSafeDatabaseUser extends Omit<DatabaseUser, 'password notifications'> {
  notifications?: PopulatedUserNotificationStatus[];
}

/**
 * Represents the a user object that only includes roles and tokenVersion.
 */
export type UserRoles = Pick<DatabaseUser, 'roles'>;
/**
 * Represents the response for user-related operations.
 * - `PopulatedSafeDatabaseUser`: A user object without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UserResponse = PopulatedSafeDatabaseUser | { error: string };

/**
 * Represents the response for role-related operations.
 * - `UserRoles` a user object that only includes roles and tokenVersion.
 * - `error`: An error message if the operation fails.
 */
export type UserRolesResponse = UserRoles | { error: string };

/**
 * Represents the response for multiple user-related operations.
 * - `PopulatedSafeDatabaseUser[]`: A list of user objects without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UsersResponse = PopulatedSafeDatabaseUser[] | { error: string };

/**
 * Express request for updating a user's biography.
 * - `username`: The username whose biography is being updated (body).
 * - `biography`: The new biography content to be set (body).
 */
export interface UpdateBiographyRequest extends Request {
  body: {
    username: string;
    biography: string;
  };
}

/**
 * Express request for updating user's login streak visibility.
 * - `username`: The username whose biography is being updated (body).
 * - `showLoginStreak`: The new visibility to be set (body).
 */
export interface UpdateShowLoginStreakRequest extends Request {
  body: {
    username: string;
    showLoginStreak: boolean;
  };
}

/**
 * Express request from user for making a transaction.
 * - `username`: The username of user making transaction (body).
 * - `cost`: cost of transaction (body).
 * - `description`: description of event requiring transaction.
 */
export interface TransactionRequest extends Request {
  body: {
    username: string;
    cost: number;
    description?: string;
  };
}

/**
 * Express request interface for marking a notification as read.
 * Extends the base Express Request with a body containing the notification ID to mark as read.
 *
 * @extends {Request}
 */
export interface ReadNotificationRequest extends Request {
  body: {
    username: string;
    notificationIds: string[];
  };
}

/*
 * Express request for updating user's status.
 * - `username`: The username whose status is being updated (body).
 * - `status`: The new status to be set (body).
 * - `customStatus`: Optional custom status message (body).
 */
export interface UpdateStatusRequest extends Request {
  body: {
    username: string;
    status: 'online' | 'busy' | 'away';
    customStatus?: string;
  };
}
